import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Reports | AJAR",
    description: "Generated by create next app",
};

export default async function ReportLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <div className="relative">
            {/* <div className="absolute right-3 sm:right-10 top-6 lg:top-7">
                <ReportDropdown />
            </div> */}
            <div className="px-4 sm:px-10">
                {children}
            </div>
        </div>
    );
}
