import { Metadata } from "next";
import AuthLayout from "@/components/auth/auth-layout"
import ForgotPasswordForm from "@/components/forms/forgot-password";

export const metadata: Metadata = {
    title: "Forgot Password | AJAR",
    description: "Generated by create next app",
};

const ForgotPassword = () => {
    return <AuthLayout
        FormComponent={<ForgotPasswordForm />}
    />
}

export default ForgotPassword
