import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Home | AJAR",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        {children}
    </>
  );
}
