import AuthLayout from "@/components/auth/auth-layout"
import { Metadata } from "next";
import TwoFactorVerificationForm from "@/components/forms/2factor";

export const metadata: Metadata = {
    title: "2FA Verification | AJAR",
    description: "Generated by create next app",
};

const TwoFactorVerification = () => {
    return <AuthLayout FormComponent={<TwoFactorVerificationForm />} />
}

export default TwoFactorVerification;
