import EmailVerificationForm from "@/components/forms/email-verification-form";
import AuthLayout from "@/components/auth/auth-layout"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Verification | AJAR",
    description: "Generated by create next app",
};

const Verification = () => {
    return <AuthLayout FormComponent={
        <EmailVerificationForm type="password" />
    } />
}

export default Verification
