import { Metadata } from "next";
import AuthLayout from "@/components/auth/auth-layout"
import ResetPasswordForm from "@/components/forms/reset-password";

export const metadata: Metadata = {
    title: "Reset Password | AJAR",
    description: "Generated by create next app",
};

const ResetPassword = () => {
    return <AuthLayout
        FormComponent={<ResetPasswordForm />}
    />
}

export default ResetPassword
