import AuthLayout from "@/components/auth/auth-layout"
import SignUpForm from "@/components/forms/signup-form"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Signup | AJAR",
  description: "Generated by create next app",
};


export default function SignUpPage() {
  return <AuthLayout
    FormComponent={<SignUpForm />}
    isVerfication={false}
  />
}
