import type React from "react"
import type { Metadata } from "next"
import './globals.css'
import { Poppins } from "next/font/google"

const poppins = Poppins({
    subsets: ["latin"],
    weight: [
        "100", "200", "300", "400", "500", "600", "700", "800", "900"
    ],
})

export const metadata: Metadata = {
    title: "Home | AJAR",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={poppins.className}>
                <main className="flex-1">{children}</main>
            </body>
        </html>
    )
}