import VerificationForm from "@/components/forms/verification-form"
import { Metadata } from "next";
import AuthLayout from "@/components/auth/auth-layout"

export const metadata: Metadata = {
    title: "Verification | AJAR",
    description: "Generated by create next app",
};

const Verification = () => {
    return <AuthLayout 
    FormComponent={<VerificationForm />} 
    />
}

export default Verification
